'use strict';
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const state={vtracerSvg:null,engineUsed:null,image:null,file:null,url:null,width:0,height:0,workW:0,workH:0,labels:null,colors:[],paths:[],edges:null,view:'original',zoom:1,mode:'image',busy:false};
const helperColors=['#9b67e4','#399cff','#f14e61','#49c275','#2ad7e5','#f4d84d','#f085b8','#83b16c','#ef9e56','#8fc8ff','#c881e1'];
function toast(m){const t=$('toast');t.textContent=m;t.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>t.style.display='none',3500)}
function status(s){$('status').textContent='● '+s;$('traceInfo').textContent=s}
function download(name,data,type){let b=data instanceof Blob?data:new Blob([data],{type});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),15000)}
function escapeXML(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
async function loadBlob(blob,name){if(!blob||!blob.type.startsWith('image/')){toast('Odaberite PNG, JPG ili WebP sliku.');return}let uri=URL.createObjectURL(blob),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=uri});}catch(e){URL.revokeObjectURL(uri);toast('Neuspješno otvaranje slike.');return}if(state.url)URL.revokeObjectURL(state.url);state.url=uri;state.image=img;state.file=blob;state.width=img.naturalWidth;state.height=img.naturalHeight;state.paths=[];state.edges=null;state.labels=null;state.colors=[];state.vtracerSvg=null;state.engineUsed=null;$('sourceImg').src=uri;$('empty').style.display='none';$('artInner').style.display='block';$('imgInfo').textContent=`${name} · ${state.width} × ${state.height}px · ${(blob.size/1048576).toFixed(2)} MB`;$('bottomLeft').textContent=`${name} — ${state.width} × ${state.height} px`;$('vectorLayer').innerHTML='';const ratio=state.width/state.height;let box=$('artboard').getBoundingClientRect();let h=Math.max(150,box.height-68),w=Math.max(150,box.width-70);if(w/h>ratio)w=h*ratio;else h=w/ratio;$('renderArea').style.width=Math.floor(w)+'px';$('renderArea').style.height=Math.floor(h)+'px';state.zoom=1;applyZoom();setView('original');status('IZVORNIK UČITAN')}
async function demo(){let r=await fetch('assets/demo.jpg');if(!r.ok)throw Error('Demo unavailable');await loadBlob(await r.blob(),'MMA mural — testni primjer.jpg')}
function applyZoom(){$('artInner').style.transform=`scale(${state.zoom})`;$('zoomText').textContent=Math.round(state.zoom*100)+'%'}
const gnum=id=>Number($(id).value);
function medianGray(im,w,h,r){if(!r)return im;let o=new Uint8Array(im.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let vals=[];for(let yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx++)vals.push(im[yy*w+xx]);vals.sort((a,b)=>a-b);o[y*w+x]=vals[vals.length>>1]}return o}
function quantize(gray,k){let centers=Array.from({length:k},(_,i)=>Math.round(255*i/(k-1)));const n=gray.length,labels=new Uint8Array(n);for(let it=0;it<7;it++){let counts=new Float64Array(k),sums=new Float64Array(k);for(let p=0;p<n;p++){let val=gray[p],best=0,dist=Infinity;for(let j=0;j<k;j++){let d=Math.abs(val-centers[j]);if(d<dist){dist=d;best=j}}labels[p]=best;sums[best]+=val;counts[best]++}for(let j=0;j<k;j++)if(counts[j])centers[j]=Math.round(sums[j]/counts[j]);}return {labels,centers}}
function simplifyPoints(points,epsilon){if(epsilon<=0||points.length<4)return points;let closed=points[0][0]===points.at(-1)[0]&&points[0][1]===points.at(-1)[1];let pts=closed?points.slice(0,-1):points;let reduced=[pts[0]];for(let i=1;i<pts.length-1;i++){let a=reduced.at(-1),b=pts[i],c=pts[i+1];if(Math.abs((b[0]-a[0])*(c[1]-b[1])-(b[1]-a[1])*(c[0]-b[0]))>epsilon)reduced.push(b)}reduced.push(pts.at(-1));return reduced}
function createGeometry(labels,w,h,k,epsilon){let all=[];let edges=[];const at=(x,y)=>x<0||y<0||x>=w||y>=h?-1:labels[y*w+x];const boundaries=Array.from({length:k},()=>[]);
 // Each grid edge belongs to the bordering region(s). All views share these coordinates.
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){let a=at(x,y),right=at(x+1,y),down=at(x,y+1);if(a!==right){const p=[x+1,y,x+1,y+1,a,right];edges.push(p);boundaries[a].push([x+1,y,x+1,y+1]);if(right>=0)boundaries[right].push([x+1,y+1,x+1,y]);}if(a!==down){let p=[x,y+1,x+1,y+1,a,down];edges.push(p);boundaries[a].push([x+1,y+1,x,y+1]);if(down>=0)boundaries[down].push([x,y+1,x+1,y+1]);}if(x===0)boundaries[a].push([0,y+1,0,y]);if(y===0)boundaries[a].push([x,y,x+1,y]);}
 for(let i=0;i<k;i++){let es=boundaries[i],adj=new Map();for(let j=0;j<es.length;j++){let e=es[j],key=e[0]+','+e[1];if(!adj.has(key))adj.set(key,[]);adj.get(key).push(j)}let used=new Uint8Array(es.length),parts=[];for(let z=0;z<es.length;z++){if(used[z])continue;let chain=[],idx=z,steps=0;while(idx!==undefined&&!used[idx]&&steps++<es.length+1){used[idx]=1;let e=es[idx];if(!chain.length)chain.push([e[0],e[1]]);chain.push([e[2],e[3]]);let next=adj.get(e[2]+','+e[3]);idx=next?.find(q=>!used[q]);if(chain.length>4&&chain.at(-1)[0]===chain[0][0]&&chain.at(-1)[1]===chain[0][1])break}if(chain.length>3){let red=simplifyPoints(chain,epsilon),d='M'+red.map(p=>p.join(' ')).join('L')+'Z';parts.push(d)}}all.push(parts.join(''))}return {paths:all,edges}}
async function traceLocal(){if(!state.image||state.busy){toast('Prvo učitaj sliku.');return}state.busy=true;$('process').disabled=true;try{status('OBRAĐUJEM SLIKU...');$('bar').style.width='14%';await new Promise(r=>setTimeout(r,30));const limit=gnum('detail'),ratio=Math.min(1,limit/Math.max(state.width,state.height));let w=Math.max(1,Math.round(state.width*ratio)),h=Math.max(1,Math.round(state.height*ratio));let c=document.createElement('canvas');c.width=w;c.height=h;let cx=c.getContext('2d',{willReadFrequently:true});cx.fillStyle='white';cx.fillRect(0,0,w,h);cx.drawImage(state.image,0,0,w,h);let pixels=cx.getImageData(0,0,w,h).data;let grayscale=new Uint8Array(w*h);for(let i=0;i<w*h;i++){let p=i*4;grayscale[i]=Math.round(.2126*pixels[p]+.7152*pixels[p+1]+.0722*pixels[p+2])}grayscale=medianGray(grayscale,w,h,gnum('smooth'));$('bar').style.width='37%';await new Promise(r=>setTimeout(r,20));let {labels,centers}=quantize(grayscale,gnum('tones'));$('bar').style.width='57%';await new Promise(r=>setTimeout(r,20));let {paths,edges}=createGeometry(labels,w,h,centers.length,gnum('simplify'));state.engineUsed='local';state.vtracerSvg=null;state.workW=w;state.workH=h;state.labels=labels;state.paths=paths;state.edges=edges;state.colors=centers.map(v=>`#${v.toString(16).padStart(2,'0').repeat(3)}`);$('palette').innerHTML=state.colors.map((c,i)=>`<i title="Ton ${i+1}: ${c}" style="background:${c}"></i>`).join('');$('bar').style.width='100%';status(`GOTOVO · ${paths.length} TONOVA · ${edges.length.toLocaleString('hr-HR')} RUBOVA`);$('bottomRight').textContent=`${w} × ${h} px · ${edges.length.toLocaleString('hr-HR')} vektorskih segmenata · BROWSER VECTOR`;setView('vector');toast('Stvarni vektorski oblici izrađeni.');}catch(e){status('POGREŠKA: '+e.message);toast(e.message)}finally{state.busy=false;$('process').disabled=false}}

function hasVTracer(){return state.engineUsed==='vtracer' && !!state.vtracerSvg}
function vtracerOnlyNotice(){toast('Outline i Kolorit za VTracer još nisu topološki izvedeni. Prebacite mehanizam na Lokalni JS i ponovno obradite sliku.');}
async function trace(){
 if($('traceEngine').value==='local')return traceLocal();
 if(!state.image || state.busy){toast('Prvo učitaj sliku.');return}
 state.busy=true;$('process').disabled=true;
 try{
  status('VTRACER WASM · OBRADA LOKALNO NA IPADU...');$('bar').style.width='15%';
  if(!window.MuralBrowserTracer?.convertPixels)throw Error('Preglednički WASM nije instaliran. Potrebna je izgradnja projekta (npm run build).');
  const limit=gnum('detail'), ratio=Math.min(1,limit/Math.max(state.width,state.height));
  const w=Math.max(1,Math.round(state.width*ratio)), h=Math.max(1,Math.round(state.height*ratio));
  const c=document.createElement('canvas');c.width=w;c.height=h;
  const ctx=c.getContext('2d',{willReadFrequently:true});
  ctx.fillStyle='#ffffff';ctx.fillRect(0,0,w,h);ctx.drawImage(state.image,0,0,w,h);
  const rgba=ctx.getImageData(0,0,w,h).data;
  $('bar').style.width='35%';
  // All pixels, vectorization and WASM processing stay on this device.
  const raw=await window.MuralBrowserTracer.convertPixels(rgba,w,h,{
    mode:$('traceMode').value,
    clustering:$('traceCluster').value,
    hierarchical:'cutout',
    maxColors:Math.round(gnum('tones')),
    simplify:gnum('simplify'),
    filterSpeckle:Math.round(gnum('smooth')),
    onProgress:progress=>{const f=Number(progress?.fraction);if(Number.isFinite(f))$('bar').style.width=(35+Math.max(0,Math.min(1,f))*55).toFixed(0)+'%';}
  });
  if(typeof raw!=='string' || !/<svg\b/i.test(raw) || !/<path\b/i.test(raw))throw Error('WASM nije vratio SVG s putanjama.');
  const doc=new DOMParser().parseFromString(raw,'image/svg+xml');
  if(doc.querySelector('parsererror,script,foreignObject,image,iframe,object,animate,animateMotion,animateTransform'))throw Error('Nesiguran ili neispravan SVG');
  for(const el of doc.querySelectorAll('*'))for(const at of [...el.attributes])if(/^on/i.test(at.name)||/^(href|xlink:href)$/i.test(at.name)||/url\s*\(/i.test(at.value))throw Error('Nedopušten SVG atribut');
  state.vtracerSvg=new XMLSerializer().serializeToString(doc.documentElement);
  state.engineUsed='vtracer';state.paths=[];state.edges=null;state.workW=w;state.workH=h;
  const count=doc.querySelectorAll('path').length;
  $('bar').style.width='100%';status(`VTRACER BROWSER WASM · ${count} STVARNIH PUTANJA`);
  $('bottomRight').textContent=`LOKALNI WASM · ${w} × ${h}px · ${count} SVG putanja`;
  setView('vector');toast('SVG izrađen lokalno. Outline i Kolorit za VTracer još nisu povezani s geometrijom.');
 }catch(e){console.error('BROWSER_WASM_TRACE',e);status('VTRACER WASM POGREŠKA: '+e.message);toast('VTracer: '+e.message);}
 finally{state.busy=false;$('process').disabled=false}
}
function svgPaths(mode){const w=state.workW,h=state.workH,paths=state.paths,cs=state.colors;if(!paths.length)return '';let parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">`,`<rect width="100%" height="100%" fill="#ffffff"/>`];if(['vector','tones','kolorit'].includes(mode)){for(let i=0;i<paths.length;i++){let base=cs[i],fill=base;if(mode==='kolorit'&&i>0&&i<paths.length-1){let anth=gnum('tones')>=5&&i===1;if(anth)fill=$('anthracite').value;else fill=helperColors[(i-2+helperColors.length)%helperColors.length]}let alpha=mode==='kolorit'&&i>1&&i<paths.length-1?gnum('colorOpacity')/100:1;parts.push(`<path id="tone-${i}" d="${paths[i]}" fill="${fill}" fill-opacity="${alpha}" fill-rule="evenodd"/>`)}}
 if(['outline','boundaries','kolorit'].includes(mode)){if(mode!=='kolorit')parts.push('<rect width="100%" height="100%" fill="white"/>');let main=[],secondary=[];const seen=new Set();for(let e of state.edges){let [x1,y1,x2,y2,a,b]=e;const key=x1+','+y1+','+x2+','+y2;if(seen.has(key))continue;seen.add(key);const isMain=b<0||a===0||b===0||a===paths.length-1||b===paths.length-1; (isMain?main:secondary).push(`M${x1} ${y1}L${x2} ${y2}`)}let burgundy=mode!=='outline'&&$('showBurgundy').checked,black=$('showBlack').checked;if(burgundy)parts.push(`<path d="${secondary.join('')}" stroke="#800020" stroke-opacity="${gnum('opacity')/100}" stroke-width="${gnum('edgeWidth')}" fill="none"/>`);if(black)parts.push(`<path d="${main.join('')}" stroke="#000" stroke-width="1.3" fill="none"/>`)}parts.push('</svg>');return parts.join('')}
function gridSvg(){if(!$('showGrid').checked||!state.image)return '';let w=state.workW||state.width,h=state.workH||state.height,wallW=gnum('wallW'),wallH=gnum('wallH'),step=gnum('gridStep');if(!wallW||!wallH||!step)return '';let sw=w/wallW,sh=h/wallH,lines=[];for(let x=0;x<wallW&&lines.length<150;x+=step)lines.push(`<line x1="${(x*sw).toFixed(2)}" y1="0" x2="${(x*sw).toFixed(2)}" y2="${h}"/>`);for(let y=0;y<wallH&&lines.length<300;y+=step)lines.push(`<line x1="0" y1="${(y*sh).toFixed(2)}" x2="${w}" y2="${(y*sh).toFixed(2)}"/>`);return `<svg viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg"><g stroke="#dc883d" stroke-width="0.7" stroke-opacity="0.85">${lines.join('')}</g></svg>`}
function setView(view){if(hasVTracer()&&!['original','vector','compare'].includes(view)){vtracerOnlyNotice();view='vector'}state.view=view;$$('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));$('sourceImg').style.display=view==='original'||view==='compare'?'block':'none';if(!state.image)return;let mode=view==='compare'?'vector':view==='original'?'':view;if(!state.paths.length&&!hasVTracer()&&mode){$('sourceImg').style.display='block';$('vectorLayer').innerHTML='';$('viewStatus').textContent='PRVO GENERIRAJ VEKTOR';return}if(mode){$('vectorLayer').innerHTML=hasVTracer()?state.vtracerSvg:svgPaths(mode);$('vectorLayer').style.opacity=view==='compare'?'0.55':'1'}else $('vectorLayer').innerHTML='';$('gridLayer').innerHTML=gridSvg();$('viewStatus').textContent=({original:'IZVORNIK · NEIZMIJENJEN',vector:'STVARNE SVG PUTANJE',outline:'GLAVNE CRNE KONTURE',boundaries:'KONTURE · JEDINSTVENA GEOMETRIJA',kolorit:'POMOĆNA KARTA TONOVA',tones:'IZVORNE TONSKE KLASE',compare:'PREKLAPANJE 55%'})[view]}
function exportSVG(view){if(hasVTracer()){download('mural_vtracer.svg',state.vtracerSvg,'image/svg+xml');return}if(!state.paths.length){toast('Najprije generiraj vektor.');return}download(`mural_${view}.svg`,svgPaths(view),'image/svg+xml')}
function exportPNG(){if(!state.image)return;let w=state.workW||state.width,h=state.workH||state.height,c=document.createElement('canvas');c.width=w;c.height=h;let ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,w,h);if(state.view==='original'){ctx.drawImage(state.image,0,0,w,h);c.toBlob(b=>download('mural_original.png',b,'image/png'));return}let svg=hasVTracer()?state.vtracerSvg:svgPaths(state.view==='compare'?'vector':state.view);let img=new Image(),u=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));img.onload=()=>{ctx.drawImage(img,0,0);URL.revokeObjectURL(u);c.toBlob(b=>download(`mural_${state.view}.png`,b,'image/png'))};img.onerror=()=>toast('PNG izvoz nije uspio.');img.src=u}
function projectJSON(){return JSON.stringify({app:'MURAL TRACE PRO',version:'5.0 working build',engine:state.engineUsed==='vtracer'?'VTracer via in-browser WASM and Web Worker (local, no API)':'in-browser grayscale quantization + polygon boundary tracing (NOT VTracer)',image:{width:state.width,height:state.height},trace:{width:state.workW,height:state.workH,tones:gnum('tones'),detail:gnum('detail'),simplification:gnum('simplify'),smoothing:gnum('smooth')},colors:state.colors,regionCount:state.paths.length,edgeCount:state.edges?.length||0,wall:{width_m:gnum('wallW'),height_m:gnum('wallH'),grid_step_m:gnum('gridStep')},exported:new Date().toISOString()},null,2)}
function saveJSON(){download('mural_project.json',projectJSON(),'application/json')}
function exportAll(){if(!state.paths.length){toast('Najprije generiraj vektor.');return}for(const mode of ['vector','outline','boundaries','kolorit','tones'])exportSVG(mode);saveJSON();toast('Radni prikazi izvezeni kao odvojene datoteke. ZIP nije implementiran.');}
function mode(m){state.mode=m;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('sectionHead').textContent=({image:'ULAZNA SLIKA',vector:'VEKTORIZACIJA',outline:'OUTLINE',kolorit:'KOLORIT PRO',vr:'PRIPREMA ZIDA',export:'IZVOZ',ai:'AI STATUS'})[m];if(m==='vector')setView('vector');if(m==='outline')setView('boundaries');if(m==='kolorit')setView('kolorit');if(m==='export')$('exportPanel').scrollIntoView({block:'nearest',behavior:'smooth'});if(m==='ai')$('aiPanel').scrollIntoView({block:'nearest',behavior:'smooth'});if(m==='vr'){$('wallPanel').scrollIntoView({block:'nearest',behavior:'smooth'});setView('boundaries')}}
$('fileInput').onchange=e=>loadBlob(e.target.files[0],e.target.files[0]?.name);$('demo').onclick=$('emptyDemo').onclick=()=>demo().catch(e=>toast(e.message));$('process').onclick=trace;$$('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));['edgeWidth','opacity','colorOpacity','showBlack','showBurgundy','showGrid','wallW','wallH','gridStep','anthracite'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='edgeWidth')$('edgeOut').textContent=$(id).value+' px';if(id==='opacity')$('opacityOut').textContent=$(id).value+'%';if(id==='colorOpacity')$('colorOpacityOut').textContent=$(id).value+'%';setView(state.view)}));['tones','detail','simplify','smooth'].forEach(id=>$(id).addEventListener('input',()=>{$(id+'Out').textContent=$(id).value+(id==='detail'?' px':'')}));$('topExport').onclick=()=>mode('export');$('saveProject').onclick=saveJSON;$('allExport').onclick=exportAll;$$('[data-export]').forEach(b=>b.onclick=()=>{if(b.dataset.export==='svg')exportSVG(state.view==='original'?'vector':state.view);if(b.dataset.export==='png')exportPNG();if(b.dataset.export==='json')saveJSON();if(b.dataset.export==='original'&&state.file)download('original'+(state.file.type==='image/png'?'.png':'.jpg'),state.file,state.file.type)});$('zoomIn').onclick=()=>{state.zoom=Math.min(5,state.zoom*1.25);applyZoom()};$('zoomOut').onclick=()=>{state.zoom=Math.max(.25,state.zoom/1.25);applyZoom()};$('resetView').onclick=()=>{state.zoom=1;applyZoom()};let drag=null;$('artboard').addEventListener('pointerdown',e=>{if(!state.image)return;drag={x:e.clientX,y:e.clientY,dx:0,dy:0};$('artboard').setPointerCapture(e.pointerId)});$('artboard').addEventListener('pointermove',e=>{if(!drag)return;let x=e.clientX-drag.x,y=e.clientY-drag.y;$('artInner').style.translate=x+'px '+y+'px'});$('artboard').addEventListener('pointerup',()=>{if(!drag)return;const tr=getComputedStyle($('artInner')).translate;drag=null});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
// Dependency-free ZIP (STORE method), preserving raw vector XML and original image.
function crc32(bytes){let c=0xffffffff;for(let b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function makeZIP(items){let entries=[],local=[],central=[],offset=0,encoder=new TextEncoder();const u16=(d,i,v)=>d.setUint16(i,v,true),u32=(d,i,v)=>d.setUint32(i,v>>>0,true);for(let [name,bytes] of items){let file=encoder.encode(name),crc=crc32(bytes),lh=new Uint8Array(30+file.length),v=new DataView(lh.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x800);u16(v,8,0);u32(v,14,crc);u32(v,18,bytes.length);u32(v,22,bytes.length);u16(v,26,file.length);lh.set(file,30);local.push(lh,bytes);let ch=new Uint8Array(46+file.length),cv=new DataView(ch.buffer);u32(cv,0,0x02014b50);u16(cv,4,20);u16(cv,6,20);u16(cv,8,0x800);u32(cv,16,crc);u32(cv,20,bytes.length);u32(cv,24,bytes.length);u16(cv,28,file.length);u32(cv,42,offset);ch.set(file,46);central.push(ch);offset+=lh.length+bytes.length}let clen=central.reduce((a,b)=>a+b.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);u32(ev,0,0x06054b50);u16(ev,8,items.length);u16(ev,10,items.length);u32(ev,12,clen);u32(ev,16,offset);return new Blob([...local,...central,end],{type:'application/zip'})}
async function exportPackage(){if(hasVTracer()){let enc=new TextEncoder(),items=[['vector_final_vtracer.svg',enc.encode(state.vtracerSvg)],['project.json',enc.encode(projectJSON())],['original.'+(state.file.type==='image/png'?'png':state.file.type==='image/webp'?'webp':'jpg'),new Uint8Array(await state.file.arrayBuffer())],['manifest.json',enc.encode(JSON.stringify({engine:'VTracer browser WASM',geometry:'VTracer vector only; no claim of aligned outline / Kolorit',generated:new Date().toISOString()},null,2))]];download('MURAL_TRACE_PRO_V5_2_BROWSER_WASM.zip',makeZIP(items),'application/zip');return}if(!state.paths.length){toast('Najprije generiraj vektor.');return}let enc=new TextEncoder(),items=[];for(let mode of ['vector','outline','boundaries','kolorit','tones'])items.push([`mural_${mode}.svg`,enc.encode(svgPaths(mode))]);items.push(['project.json',enc.encode(projectJSON())]);items.push(['palette.json',enc.encode(JSON.stringify(state.colors.map((hex,i)=>({classId:i,hex,helper:i>1&&i<state.colors.length-1?helperColors[(i-2+helperColors.length)%helperColors.length]:null})),null,2))]);let extension=state.file.type==='image/png'?'png':state.file.type==='image/webp'?'webp':'jpg';items.push([`original.${extension}`,new Uint8Array(await state.file.arrayBuffer())]);let manifest={version:'5.0 browser build',vectorEngine:'LOCAL_JS_CONTOUR_NOT_VTRACER',fileCount:items.length+1,generated:new Date().toISOString(),unimplemented:['AI image service','professional node editor','face-aware segmentation']};items.push(['manifest.json',enc.encode(JSON.stringify(manifest,null,2))]);download('MURAL_TRACE_PRO_V5_PROJECT.zip',makeZIP(items),'application/zip');toast('ZIP paket uspješno pripremljen.')}
$('traceEngine').addEventListener('change',()=>{$('engineName').textContent=$('traceEngine').value==='vtracer'?'VTRACER WASM':'LOCAL JS';});$('allExport').onclick=()=>exportPackage().catch(e=>toast('ZIP pogreška: '+e.message));
